import { formThemeSchema } from "../schema";
import type { FormTheme } from "../schema";

const rawPresets: ReadonlyArray<FormTheme> = [
  {
    presetId: "lab",
    primaryColor: "#3b82f6",
    accentColor: "#8b5cf6",
    backgroundColor: "#ffffff",
    textColor: "#0f172a",
    emoji: "🧪",
    borderRadius: "md",
    borderRadiusForm: "md",
    borderRadiusInput: "md",
    borderRadiusButton: "md",
    fontFamily: "sans",
    headingFontFamily: "sans",
    spacing: "normal",
    pattern: "dots",
    logoPosition: "left",
    titleAlignment: "left",
    submitAnimation: "none",
    fieldEntranceAnimation: "none",
    submitLabel: "Enviar",
    cardStyle: "flat",
    showProgressBar: false,
    shadow: "md",
    borderWidth: "thin",
    borderColor: "#e2e8f0",
    backgroundOpacity: 100,
  },
  {
    presetId: "minimal",
    primaryColor: "#0f172a",
    accentColor: "#475569",
    backgroundColor: "#ffffff",
    textColor: "#0f172a",
    emoji: "📋",
    borderRadius: "none",
    borderRadiusForm: "none",
    borderRadiusInput: "none",
    borderRadiusButton: "none",
    fontFamily: "sans",
    headingFontFamily: "sans",
    spacing: "compact",
    pattern: "none",
    logoPosition: "left",
    titleAlignment: "left",
    submitAnimation: "none",
    fieldEntranceAnimation: "none",
    submitLabel: "Enviar",
    cardStyle: "flat",
    showProgressBar: false,
    shadow: "none",
    borderWidth: "thin",
    borderColor: "#e2e8f0",
    backgroundOpacity: 100,
  },
  {
    presetId: "playful",
    primaryColor: "#ec4899",
    accentColor: "#f59e0b",
    backgroundColor: "#fef3c7",
    textColor: "#7c2d12",
    emoji: "🎨",
    borderRadius: "full",
    borderRadiusForm: "full",
    borderRadiusInput: "full",
    borderRadiusButton: "full",
    fontFamily: "rounded",
    headingFontFamily: "display",
    spacing: "relaxed",
    pattern: "waves",
    logoPosition: "center",
    titleAlignment: "center",
    submitAnimation: "bounce",
    fieldEntranceAnimation: "scale-in",
    submitLabel: "¡Listo!",
    cardStyle: "elevated",
    showProgressBar: true,
    shadow: "xl",
    borderWidth: "none",
    borderColor: "#fbbf24",
    backgroundOpacity: 100,
  },
  {
    presetId: "dark",
    primaryColor: "#60a5fa",
    accentColor: "#a78bfa",
    backgroundColor: "#0f172a",
    textColor: "#f1f5f9",
    emoji: "🌙",
    borderRadius: "lg",
    borderRadiusForm: "lg",
    borderRadiusInput: "lg",
    borderRadiusButton: "lg",
    fontFamily: "sans",
    headingFontFamily: "mono",
    spacing: "normal",
    pattern: "grid",
    logoPosition: "left",
    titleAlignment: "left",
    submitAnimation: "pulse",
    fieldEntranceAnimation: "fade-up",
    submitLabel: "Enviar",
    cardStyle: "glass",
    showProgressBar: false,
    shadow: "lg",
    borderWidth: "thin",
    borderColor: "#334155",
    backgroundOpacity: 100,
  },
  {
    presetId: "academic",
    primaryColor: "#7c3aed",
    accentColor: "#4f46e5",
    backgroundColor: "#faf5ff",
    textColor: "#1e1b4b",
    emoji: "📚",
    borderRadius: "sm",
    borderRadiusForm: "sm",
    borderRadiusInput: "sm",
    borderRadiusButton: "sm",
    fontFamily: "serif",
    headingFontFamily: "serif",
    spacing: "relaxed",
    pattern: "none",
    logoPosition: "left",
    titleAlignment: "left",
    submitAnimation: "none",
    fieldEntranceAnimation: "none",
    submitLabel: "Enviar",
    cardStyle: "flat",
    showProgressBar: false,
    shadow: "sm",
    borderWidth: "thin",
    borderColor: "#e9d5ff",
    backgroundOpacity: 100,
  },
  {
    presetId: "tropical",
    primaryColor: "#10b981",
    accentColor: "#06b6d4",
    backgroundColor: "#ecfdf5",
    textColor: "#064e3b",
    emoji: "🌴",
    borderRadius: "xl",
    borderRadiusForm: "xl",
    borderRadiusInput: "xl",
    borderRadiusButton: "xl",
    fontFamily: "rounded",
    headingFontFamily: "rounded",
    spacing: "normal",
    pattern: "dots",
    logoPosition: "center",
    titleAlignment: "center",
    submitAnimation: "confetti",
    fieldEntranceAnimation: "fade-up",
    submitLabel: "Enviar",
    cardStyle: "elevated",
    showProgressBar: true,
    shadow: "lg",
    borderWidth: "none",
    borderColor: "#6ee7b7",
    backgroundOpacity: 100,
  },
  {
    presetId: "racing",
    primaryColor: "#dc2626",
    accentColor: "#facc15",
    backgroundColor: "#111827",
    textColor: "#f9fafb",
    emoji: "🏁",
    borderRadius: "lg",
    borderRadiusForm: "lg",
    borderRadiusInput: "lg",
    borderRadiusButton: "lg",
    fontFamily: "display",
    headingFontFamily: "display",
    spacing: "normal",
    pattern: "checkered",
    logoPosition: "center",
    titleAlignment: "center",
    submitAnimation: "race",
    fieldEntranceAnimation: "race-in",
    submitLabel: "¡A la carrera!",
    cardStyle: "glass",
    showProgressBar: true,
    shadow: "xl",
    borderWidth: "medium",
    borderColor: "#dc2626",
    backgroundOpacity: 100,
  },
  {
    presetId: "party",
    primaryColor: "#d946ef",
    accentColor: "#f97316",
    backgroundColor: "#4c1d95",
    textColor: "#ffffff",
    emoji: "🎈",
    borderRadius: "full",
    borderRadiusForm: "full",
    borderRadiusInput: "full",
    borderRadiusButton: "full",
    fontFamily: "rounded",
    headingFontFamily: "display",
    spacing: "relaxed",
    pattern: "stars",
    logoPosition: "center",
    titleAlignment: "center",
    submitAnimation: "confetti",
    fieldEntranceAnimation: "flip-in",
    submitLabel: "¡Celebrar!",
    cardStyle: "elevated",
    showProgressBar: true,
    shadow: "2xl",
    borderWidth: "none",
    borderColor: "#d946ef",
    backgroundOpacity: 100,
  },
  {
    presetId: "neon",
    primaryColor: "#22d3ee",
    accentColor: "#e879f9",
    backgroundColor: "#020617",
    textColor: "#e2e8f0",
    emoji: "⚡",
    borderRadius: "lg",
    borderRadiusForm: "lg",
    borderRadiusInput: "lg",
    borderRadiusButton: "lg",
    fontFamily: "mono",
    headingFontFamily: "display",
    spacing: "normal",
    pattern: "carbon",
    logoPosition: "left",
    titleAlignment: "left",
    submitAnimation: "pulse",
    fieldEntranceAnimation: "slide-left",
    submitLabel: "Iniciar",
    cardStyle: "glass",
.
.
.
    backgroundOpacity: 100,
  },
];

export const FORM_THEME_PRESETS: ReadonlyArray<FormTheme> = rawPresets.map(
  (preset, index) => {
    const parsed = formThemeSchema.safeParse(preset);
    if (!parsed.success) {
      throw new Error(
        `Preset at index ${index} (presetId: ${preset.presetId ?? "unknown"}) is invalid: ${parsed.error.message}`
      );
    }
    return parsed.data;
  }
);
